### ISSUE TITLE
CSS not being applied to buttons/cards for e-commerce website

### ISSUE THREAD

**Issue by patricia568** [patricia568/ecommerce-pattern-library#2]
Hello @thomasjbradley !

I'm having a little bit of trouble with my css code not being applied to my pattern library for the e-commerce website. I can't seem to get my buttons and/or cards to apply the css styling and I'm wondering if I could get some help figuring out why. The styling (fonts and background colours) seem to be working on all the other parts of the website (like headings) except for the buttons and cards.

Here's the code from my html & css files:

**_basic.html_**
<a class="btn" href="#">Shop now</a>

**_ghost.html_**
<a class="btn btn-ghost" href="#">Shop</a>
 
**_light.html_**
<a class="btn btn-light" href="#">Sign up</a>

<img width="1129" alt="screenshot 2019-01-31 17 45 47" src="https://user-images.githubusercontent.com/31852223/52090698-19c6a080-2580-11e9-89a3-c6d10a84f405.png">

**_buttons.css_**
.btn {
  background-color: var(--color-primary);
  color: var(--color-secondary);
}

.btn:hover {
  background-color: var(--color-primary-light);
}

.btn-ghost {
  background-color: var(--color-neutral-grey);
  color: var(--color-secondary);
}

.btn-ghost:hover {
  background-color: var(--color-primary-light);
}

.btn-light {
  background-color: var(--color-primary-light);
  color: var(--color-secondary);
}

.btn-light:hover {
  background-color: var(--color-primary);
}

<img width="844" alt="screenshot 2019-01-31 17 49 19" src="https://user-images.githubusercontent.com/31852223/52090863-935e8e80-2580-11e9-9945-b5fbf08850c3.png">

<img width="666" alt="screenshot 2019-01-31 17 04 54" src="https://user-images.githubusercontent.com/31852223/52089595-fd753480-257c-11e9-99fa-ebcfbcbb6bd4.png">

<img width="291" alt="screenshot 2019-01-31 17 23 26" src="https://user-images.githubusercontent.com/31852223/52089596-fd753480-257c-11e9-92c9-514bcb84d703.png">

Thank you! :)

**Comment by thomasjbradley** [comment]
I think it’s because your `main.css` file is empty.

Delete these lines from `theme.css`:
https://github.com/patricia568/ecommerce-pattern-library/blob/master/css/theme.css#L17-L21
They should be inside `main.css`—with two lines of triple dashes at the top, refer to this:
https://learn-the-web.algonquindesign.ca/courses/web-dev-4/pattern-library-set-up/#step-9
